import { NextRequest, NextResponse } from "next/server";

function formatCurrency(n: number): string {
  return new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD" }).format(n);
}

export async function POST(req: NextRequest) {
  try {
    const data = await req.json();

    const findingsRows = (data.findings || [])
      .map(
        (f: { description: string; category: string; amount: number; loopAlternative: string }) => `
        <tr>
          <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:14px;">${f.description}</td>
          <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:13px;color:#666;">${f.category}</td>
          <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:14px;font-weight:600;color:#dc2626;text-align:right;">${formatCurrency(f.amount)}</td>
          <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:13px;color:#004639;">${f.loopAlternative}</td>
        </tr>`
      )
      .join("");

    const planRows = (data.planComparison || [])
      .map(
        (p: { plan: string; monthlyFee: number; fxRate: number; annualCostOnPlan: number; annualSavingsVsBank: number; recommended: boolean }) => `
        <tr style="${p.recommended ? "background:#C4F6C6;" : ""}">
          <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:14px;font-weight:${p.recommended ? "700" : "400"};">${p.plan}${p.recommended ? " ⭐" : ""}</td>
          <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:14px;text-align:right;">${p.monthlyFee === 0 ? "Free" : `$${p.monthlyFee}/mo`}</td>
          <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:14px;text-align:right;">${p.fxRate}%</td>
          <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:14px;text-align:right;">${formatCurrency(p.annualCostOnPlan)}</td>
          <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-size:14px;font-weight:600;color:#004639;text-align:right;">${formatCurrency(p.annualSavingsVsBank)}</td>
        </tr>`
      )
      .join("");

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Loop FX Audit Report — ${data.bankName || "Bank"}</title>
</head>
<body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#f9fafb;color:#1a1a1a;">
  <div style="max-width:800px;margin:0 auto;background:white;">
    <!-- Header -->
    <div style="background:#004639;padding:32px 40px;">
      <h1 style="margin:0;color:white;font-size:24px;font-weight:700;">🩸 FX Audit Report</h1>
      <p style="margin:8px 0 0;color:rgba(255,255,255,0.7);font-size:14px;">Generated by Bleed — powered by Loop</p>
    </div>

    <div style="padding:32px 40px;">
      <!-- Bank Info -->
      <div style="margin-bottom:32px;">
        <p style="margin:0;font-size:14px;color:#666;">Bank: <strong>${data.bankName || "Unknown"}</strong></p>
        <p style="margin:4px 0 0;font-size:14px;color:#666;">Period: ${data.statementPeriod || "N/A"}</p>
      </div>

      <!-- Summary -->
      <div style="display:flex;gap:16px;margin-bottom:32px;flex-wrap:wrap;">
        <div style="flex:1;min-width:150px;background:#fef2f2;border:1px solid #fecaca;border-radius:12px;padding:16px;">
          <p style="margin:0;font-size:12px;color:#666;text-transform:uppercase;">Fees Found</p>
          <p style="margin:4px 0 0;font-size:24px;font-weight:700;color:#dc2626;">${formatCurrency(data.summary?.totalFeesFound || 0)}</p>
        </div>
        <div style="flex:1;min-width:150px;background:#fef2f2;border:1px solid #fecaca;border-radius:12px;padding:16px;">
          <p style="margin:0;font-size:12px;color:#666;text-transform:uppercase;">Annual Projection</p>
          <p style="margin:4px 0 0;font-size:24px;font-weight:700;color:#dc2626;">${formatCurrency(data.summary?.annualProjection || 0)}</p>
        </div>
        <div style="flex:1;min-width:150px;background:#f0fdf4;border:1px solid #bbf7d0;border-radius:12px;padding:16px;">
          <p style="margin:0;font-size:12px;color:#666;text-transform:uppercase;">You&apos;d Save / Year</p>
          <p style="margin:4px 0 0;font-size:24px;font-weight:700;color:#004639;">${formatCurrency(data.summary?.annualSavings || 0)}</p>
        </div>
      </div>

      <!-- Findings -->
      ${(data.findings || []).length > 0 ? `
      <h2 style="font-size:18px;font-weight:700;margin:0 0 16px;color:#004639;">What We Found</h2>
      <table style="width:100%;border-collapse:collapse;margin-bottom:32px;">
        <thead>
          <tr style="background:#f9fafb;">
            <th style="padding:10px 12px;text-align:left;font-size:12px;color:#666;text-transform:uppercase;border-bottom:2px solid #e5e7eb;">Description</th>
            <th style="padding:10px 12px;text-align:left;font-size:12px;color:#666;text-transform:uppercase;border-bottom:2px solid #e5e7eb;">Category</th>
            <th style="padding:10px 12px;text-align:right;font-size:12px;color:#666;text-transform:uppercase;border-bottom:2px solid #e5e7eb;">Amount</th>
            <th style="padding:10px 12px;text-align:left;font-size:12px;color:#666;text-transform:uppercase;border-bottom:2px solid #e5e7eb;">Loop Alternative</th>
          </tr>
        </thead>
        <tbody>${findingsRows}</tbody>
      </table>` : ""}

      <!-- Plan Comparison -->
      ${(data.planComparison || []).length > 0 ? `
      <h2 style="font-size:18px;font-weight:700;margin:0 0 16px;color:#004639;">Your Bank vs Loop</h2>
      <table style="width:100%;border-collapse:collapse;margin-bottom:32px;">
        <thead>
          <tr style="background:#f9fafb;">
            <th style="padding:10px 12px;text-align:left;font-size:12px;color:#666;text-transform:uppercase;border-bottom:2px solid #e5e7eb;">Plan</th>
            <th style="padding:10px 12px;text-align:right;font-size:12px;color:#666;text-transform:uppercase;border-bottom:2px solid #e5e7eb;">Monthly Fee</th>
            <th style="padding:10px 12px;text-align:right;font-size:12px;color:#666;text-transform:uppercase;border-bottom:2px solid #e5e7eb;">FX Rate</th>
            <th style="padding:10px 12px;text-align:right;font-size:12px;color:#666;text-transform:uppercase;border-bottom:2px solid #e5e7eb;">Annual Cost</th>
            <th style="padding:10px 12px;text-align:right;font-size:12px;color:#666;text-transform:uppercase;border-bottom:2px solid #e5e7eb;">Savings vs Bank</th>
          </tr>
        </thead>
        <tbody>${planRows}</tbody>
      </table>` : ""}

      <!-- CTA -->
      <div style="text-align:center;padding:32px 0;border-top:1px solid #e5e7eb;">
        <p style="font-size:16px;color:#666;margin:0 0 16px;">Ready to stop overpaying?</p>
        <a href="https://go.bankonloop.com/signup" style="display:inline-block;background:#004639;color:white;padding:14px 32px;border-radius:12px;text-decoration:none;font-weight:600;font-size:16px;">Open a Free Loop Account →</a>
      </div>

      <p style="font-size:11px;color:#999;text-align:center;margin-top:24px;">Report generated by bleed.bankonloop.com</p>
    </div>
  </div>
</body>
</html>`;

    return new NextResponse(html, {
      status: 200,
      headers: {
        "Content-Type": "text/html",
        "Content-Disposition": `attachment; filename="loop-audit-report.html"`,
      },
    });
  } catch {
    return NextResponse.json({ error: "Invalid request" }, { status: 400 });
  }
}
